### ISSUE TITLE
How do you know the MMR of the last match?

### ISSUE THREAD

**Issue by giulianimartini** [DarkIceXD/DarkIceXD.github.io#1]
Hi DarkIce,

how do you know the last MMR for each match on the attributes.xml file?

Checking the xml file, I noted 3 different mmrs for my username.

Thanks in advance.

**Comment by DarkIceXD** [comment]
first you need to find "MissionBagNumTeams" this will be your team count

now you need to search for "MissionBagTeam_X_numplayers" where X is your team count from 0 to the value from "MissionBagNumTeams" - 1 here you can find the number of players in the team

now you can search for "MissionBagPlayer_X_Y_blood_line_name" and "MissionBagPlayer_X_Y_mmr" where X is the team number from before and Y is the team member going from 0 to the value of "MissionBagTeam_X_numplayers" - 1



also this is not an issue. please refrain from posting issues like this.
